### ISSUE TITLE
Documentation on configuration

### ISSUE THREAD

**Issue by HazWard** [klemens/radicale-auth-seafile#1]
I'm interested in using this plugin with my Radicale setup but there are no instructions on how to set it up to use the current authentication system in Seafile. Would you mind sharing that information (maybe adding a usage section in a README file) ?

Thanks in advance!

**Comment by klemens** [comment]
Setup is actually quite easy. Just install the module (there is also an [arch package](https://aur.archlinux.org/packages/python-radicale-auth-seafile/) and I could also put this on PyPI if it helps) and add the following to your radicale config (you need at least version 2):
```
[auth]
type = radicale_auth_seafile
seafile_db = postgres://username:password@localhost/ccnet_db
```

The main problem is that it currently only supports postgresql and not mysql or sqlite. But I guess supporting those wouldn't be very difficult.
